### ISSUE TITLE
Error 500 after installing FB SDK

### ISSUE THREAD

**Issue by fsopm** [rmuilwijk/MauticFBAdsCustomAudiencesBundle#4]
Hi there, 
thanks for your work. 

I have tried to install the plugin but I'm stuck at the fist step. 
I have well installed the FB SDK but then, Mautic is not available. 

Here is the error log:

```
[13-Jan-2020 15:19:01 UTC] PHP Fatal error:  Uncaught Error: Class 'Mautic\ApiBundle\MauticApiBundle' not found in /home/XXXXX/public_html/app/AppKernel.php:169
Stack trace:
#0 /home/XXXXX/public_html/vendor/symfony/http-kernel/Kernel.php(431): AppKernel->registerBundles()
#1 /home/XXXXX/public_html/app/AppKernel.php(273): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /home/XXXXX/public_html/vendor/symfony/framework-bundle/Console/Application.php(62): AppKernel->boot()
#3 /home/XXXXX/public_html/vendor/symfony/console/Application.php(117): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/XXXXX/public_html/app/console(40): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}
  thrown in /home/XXXXX/public_html/app/AppKernel.php on line 169
```

Have you ever faced that kind of issue? 
I use the version 2.15.3 of Mautic. 

Thanks

**Comment by consultor360** [comment]
Hello did you manage to solve the integration problem?

**Comment by fsopm** [comment]
Hi @consultor360,
not at all and moreover, it seems it broke our mautic installation. 
After the install of the module, our subscribers received the same campaign email more than 5 times.
